#!/bin/bash
sudo apt update && sudo apt upgrade -y
sudo apt-get install -y \
snapd \
unzip \
zip \
netcat \
python3 \
python3-dev \
python3-pip \
terminator \
tmux \
whois \
rsync \
nmap \
hydra \
steghide \
gobuster \
binwalk \
exiftool \
hexedit \
tcpdump;

sudo snap install \
john-the-ripper

sudo snap install \
cool-retro-term --classic

sudo pip3 install \
sqlmap \
requests \
pynvim

